### ISSUE TITLE
Totally not working

### ISSUE THREAD

**Issue by Immons** [onovotny/fluentassertions#3]
![fluentshouldnotexists](https://cloud.githubusercontent.com/assets/7934036/7936279/2640e414-0938-11e5-8a5c-427299efc748.jpg)

I don't know why, but Xamarin version is totally not working for me. FluentAssertions in non-xamarin projects are fine, these aren't.

**Comment by clairernovotny** [comment]
Can you please try again with the latest? Closing for now without a repro.
